site_name: Simon’s Blog
site_author: SimonSun
site_description: Simon的个人博客
site_url: https://tendo33.github.io/Simons-site/
repo_url: https://github.com/Tendo33
repo_name: Simon's Blog
edit_uri: Simons-site/blob/main/docs/ # 编辑路径

theme:
  name: material
  logo: assets/images/小狗子.png
  #palette:
  #primary: light blue
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/dog_02.png

  icon:
    repo: fontawesome/brands/github #右上角图标

plugins:
  - tags
  - mkdocs-video
  ## 图片放大插件
  - glightbox:
      effect: zoom
      zoomable: true
      draggable: true
      skip_classes:
        - nonzoom
  ## 文章日期插件
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: True
      allow_errors: false
      ignore: ["name.ipynb"]
      #execute_ignore: "path/*.ipynb"
  - search:
      lang:
        - en
        # 日语搜索汉字
        #- zh 中文暂不支持
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - rss

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件


  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: "\ue157"

extra_javascript:
  # 百度的页面访问统计【暂时移除百度的访问统计（加载实在是有点慢】
  - assets/javascripts/baidu.js

  # 数学公式格式支持，用html嵌入的方式支持数学公式
  ### mathjax2.7.1
  ### 使用https://codepen.io/pkra/pen/EPeKjo这个项目的代码实现自动换行
  ###（这个特性mathjax3似乎要支持但是现在还没实现
  - assets/javascripts/mathjax.js

  # 随着星期几改变主题颜色
  #- assets/javascripts/color.js
  # 下雪特效
  #- https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/snow3.js
  # 鼠标点击特效
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.1.3/js/maodian.js
  - "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"

#extra_css:

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tendo33
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/40973308?spm_id_from=333.1007.0.0
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SimonSun33
    - icon: fontawesome/solid/paper-plane
      link: https://simonsun3.notion.site/ff1982c84e844b53a20966db6ec282f2?v=9d898ec09f974b419e0aa6053070e584&pvs=4

nav:
  - Home: index.md
  - Blog:
      - Blog/index.md
      - 2022:
          - Blog/2022/2022年度总结.md
      - 2023:
          - Blog/2023/卖身oneflow.md
          - Blog/2023/读我与地坛有感.md
          - Blog/2023/读百年孤独有感.md
          #- Blog/2023/curriculum.md
          - Blog/2023/印象.md
          - Blog/2023/music.md
          - Blog/2023/记一次肠胃炎.md
          - Blog/2023/旅游.md
          - Blog/2023/重回巴黎.md
          - Blog/2023/十二月大雪弥漫.md
          - Blog/2023/北京的雪.md
          - Blog/2023/最后一天.md
      - 2024:
          - Blog/2024/第一个新年.md
  - Article:
      - Article/index.md
      - Article/常用命令行及详解.md
      - Git:
          - Article/Git/git.md
          - Article/Git/git_server.md
      - 墙和梯子:
          - Article/GFW/简介.md
          - Article/GFW/客户端.md
          - Article/GFW/DIY.md
      - mkdocs:
          - Article/mkdocs/理论.md
          - Article/mkdocs/实践.md
          - Article/mkdocs/best_practices.md
      - LaTeX:
          - Article/latex/basic_latex.md
      - Jupyter:
          - 介绍: Article/jupyter/jupyter1.md
          - 基础使用: Article/jupyter/jupyter2.md
          - 远程服务: Article/jupyter/jupyter3.md
          - 进阶使用: Article/jupyter/jupyter4.md
      - SAS:
          - SAS的基本操作: Article/SAS/SAS的基本操作.md
          - SAS的统计应用: Article/SAS/SAS的统计应用.md
  - Python:
      - Python/index.md
      - Python/python前置知识.md
      - Python/命令行.md
      - Python/脚本.md
      - 基础语法:
          - Python/基础语法/python基础语法1.md
          - Python/基础语法/python基础语法2.md
      - 高级语法:
          - Python/进阶语法/python高级语法1.md
          - Python/进阶语法/python高级语法2.md
      - 标准库:
          - Python/标准库/os.md
          - Python/标准库/re.md
          - Python/标准库/time.md
      - 第三方库:
          - Python/第三方库/包管理.md
          - Python/第三方库/numpy.md
          - Python/第三方库/pandas.md
          - Python/第三方库/自己写一个包.md
      - 应用案例（MISC）:
          - Python/应用案例/发邮件.md
      - 应用案例（爬虫）:
          - Python/应用案例/爬虫/药监局1.md
          - Python/应用案例/爬虫/药监局2.md
      - 应用案例（微软三件套）:
          - Python/应用案例/Excel/csv2xlsx.md
  - Project:
      - Project/index.md
      - Project/YOLOv5-steel-defect-detect.md
      - Project/high_school_math.md
      - Project/Tp-Cuda-LeNet5.md
      - Project/pymd.md
      - Project/YOLOv7-weed-detection.md
      - Project/LI-FI.md
  - Statistics:
      - Statistics/index.md
      - 基础课:
          - Statistics/数学分析.md
          - Statistics/线性代数.md
          - Statistics/运筹学.md
          - Statistics/概率论与数理统计.md
          - Statistics/统计软件.md
      - 专业课:
          - Statistics/统计推断.md
          - Statistics/回归分析.md
          - Statistics/时间序列分析.md
          - Statistics/抽样调查.md
          - Statistics/多元分析.md
          - Statistics/随机过程.md
          - Statistics/属性数据分析.md
          - Statistics/非参数统计.md
      - 选修课:
          - Statistics/统计计算.md
          - Statistics/数据挖掘.md
          - Statistics/模式识别和机器学习.md
  - AI_learning:
      - AI_learning/index.md
      - AI_learning/environment.md
      #- DeepLearning:
      #- DeepLearning/一道复杂极限.md
